<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Invoice - {{ $purchase->reference_no }}</title>
    <!-- Google Fonts: Poppins -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f1f5f9;
            color: #1e293b;
        }

        .invoice-card {
            max-width: 850px;
            margin: 30px auto;
            background: #ffffff;
            padding: 40px;
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05);
        }

        .invoice-header {
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 24px;
            margin-bottom: 24px;
        }

        .invoice-table th {
            background-color: #f8fafc;
            color: #475569;
            font-size: 0.8rem;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        @media print {
            body {
                background: #ffffff !important;
            }
            .invoice-card {
                box-shadow: none !important;
                padding: 0 !important;
                margin: 0 !important;
                max-width: 100% !important;
            }
            .no-print {
                display: none !important;
            }
        }
    </style>
</head>
<body>

    <!-- Action Toolbar (Hidden during print) -->
    <div class="container my-3 no-print" style="max-width: 850px;">
        <div class="d-flex justify-content-between align-items-center">
            <a href="{{ route('purchases.show', $purchase) }}" class="btn btn-outline-secondary rounded-pill px-3">
                <i class="bi bi-arrow-left me-1"></i> Back to Purchase Details
            </a>
            <div class="d-flex gap-2">
                <button onclick="window.print()" class="btn btn-primary rounded-pill px-4 shadow-sm">
                    <i class="bi bi-printer me-1"></i> Print Invoice
                </button>
            </div>
        </div>
    </div>

    <!-- Printable Invoice Sheet -->
    <div class="invoice-card">
        <!-- Top Header: Business Logo & Invoice Title -->
        <div class="invoice-header d-flex justify-content-between align-items-start">
            <div>
                <h3 class="fw-bold text-primary mb-1">
                    <i class="bi bi-shop me-2"></i> {{ config('app.name', 'POS Management') }}
                </h3>
                <p class="text-muted small mb-0">Retail & Inventory Procurement Division</p>
                <small class="text-muted">Generated by: {{ $purchase->user?->name ?? 'Administrator' }}</small>
            </div>
            <div class="text-end">
                <h4 class="fw-bold text-dark mb-1 text-uppercase">Purchase Invoice</h4>
                <div class="font-monospace fw-bold fs-5 text-primary">{{ $purchase->reference_no }}</div>
                <small class="text-muted">Date: {{ $purchase->purchase_date->format('M d, Y') }}</small>
            </div>
        </div>

        <!-- Supplier Details & Order Overview -->
        <div class="row mb-4">
            <div class="col-sm-6">
                <small class="text-muted text-uppercase fw-bold" style="font-size: 0.72rem;">Vendor / Supplier</small>
                <h5 class="fw-bold text-dark mt-1 mb-1">{{ $purchase->supplier?->name }}</h5>
                @if($purchase->supplier?->company_name)
                    <div class="text-muted small fw-semibold">{{ $purchase->supplier->company_name }}</div>
                @endif
                <div class="small text-muted mt-1">
                    @if($purchase->supplier?->address)
                        <div>{{ $purchase->supplier->address }}</div>
                    @endif
                    @if($purchase->supplier?->phone)
                        <div>Phone: {{ $purchase->supplier->phone }}</div>
                    @endif
                    @if($purchase->supplier?->email)
                        <div>Email: {{ $purchase->supplier->email }}</div>
                    @endif
                    @if($purchase->supplier?->tax_number)
                        <div>Tax ID / VAT: <code>{{ $purchase->supplier->tax_number }}</code></div>
                    @endif
                </div>
            </div>

            <div class="col-sm-6 text-sm-end mt-3 mt-sm-0">
                <small class="text-muted text-uppercase fw-bold" style="font-size: 0.72rem;">Order Status</small>
                <div class="mt-1">
                    <span class="badge bg-{{ $purchase->status_badge }}-subtle text-{{ $purchase->status_badge }} border border-{{ $purchase->status_badge }}-subtle px-3 py-1 rounded-pill text-capitalize fw-bold">
                        Goods: {{ $purchase->status }}
                    </span>
                    <span class="badge bg-{{ $purchase->payment_status_badge }}-subtle text-{{ $purchase->payment_status_badge }} border border-{{ $purchase->payment_status_badge }}-subtle px-3 py-1 rounded-pill text-capitalize fw-bold ms-1">
                        Payment: {{ $purchase->payment_status }}
                    </span>
                </div>
                <div class="small text-muted mt-2">
                    <div>Payment Method: <strong class="text-capitalize">{{ str_replace('_', ' ', $purchase->payment_method ?? 'Cash') }}</strong></div>
                    <div>Recorded Date: {{ $purchase->created_at->format('M d, Y H:i') }}</div>
                </div>
            </div>
        </div>

        <!-- Itemized Table -->
        <div class="table-responsive mb-4">
            <table class="table table-bordered invoice-table align-middle">
                <thead>
                    <tr>
                        <th style="width: 5%;">#</th>
                        <th style="width: 45%;">Item Description</th>
                        <th style="width: 15%;" class="text-end">Unit Cost</th>
                        <th style="width: 15%;" class="text-center">Quantity</th>
                        <th style="width: 20%;" class="text-end">Line Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($purchase->items as $index => $item)
                        <tr>
                            <td class="text-muted small">{{ $index + 1 }}</td>
                            <td>
                                <div class="fw-bold text-dark">{{ $item->product?->name ?? 'Product' }}</div>
                                @if($item->product?->sku)
                                    <small class="text-muted font-monospace">SKU: {{ $item->product->sku }}</small>
                                @endif
                            </td>
                            <td class="text-end fw-semibold text-muted">${{ number_format($item->unit_cost, 2) }}</td>
                            <td class="text-center fw-bold">{{ number_format($item->quantity) }}</td>
                            <td class="text-end fw-bold text-dark">${{ number_format($item->subtotal, 2) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Financial Summary -->
        <div class="row justify-content-end mb-4">
            <div class="col-sm-6">
                <table class="table table-sm table-borderless">
                    <tr>
                        <td class="text-muted">Subtotal:</td>
                        <td class="text-end fw-semibold text-dark">${{ number_format($purchase->subtotal, 2) }}</td>
                    </tr>
                    @if($purchase->tax_amount > 0)
                        <tr>
                            <td class="text-muted">Tax (+):</td>
                            <td class="text-end fw-semibold text-dark">${{ number_format($purchase->tax_amount, 2) }}</td>
                        </tr>
                    @endif
                    @if($purchase->discount_amount > 0)
                        <tr>
                            <td class="text-muted">Discount (-):</td>
                            <td class="text-end fw-semibold text-danger">-${{ number_format($purchase->discount_amount, 2) }}</td>
                        </tr>
                    @endif
                    <tr class="border-top border-dark">
                        <td class="fw-bold fs-6">Grand Total:</td>
                        <td class="text-end fw-bold text-primary fs-5">${{ number_format($purchase->total_amount, 2) }}</td>
                    </tr>
                    <tr>
                        <td class="text-muted">Amount Paid:</td>
                        <td class="text-end fw-bold text-success">${{ number_format($purchase->paid_amount, 2) }}</td>
                    </tr>
                    <tr class="border-top">
                        <td class="fw-bold text-dark">Remaining Balance Due:</td>
                        <td class="text-end fw-bold {{ $purchase->due_amount > 0 ? 'text-danger' : 'text-muted' }} fs-6">
                            ${{ number_format($purchase->due_amount, 2) }}
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        @if($purchase->notes)
            <div class="p-3 bg-light rounded-3 mb-4 small">
                <strong class="d-block text-uppercase fw-bold text-muted mb-1" style="font-size: 0.72rem;">Notes / Terms</strong>
                {{ $purchase->notes }}
            </div>
        @endif

        <!-- Footer / Signatures -->
        <div class="row mt-5 pt-4 border-top">
            <div class="col-6 text-center">
                <div class="border-top border-secondary w-75 mx-auto pt-2">
                    <small class="text-muted fw-semibold">Authorized Store Representative</small>
                </div>
            </div>
            <div class="col-6 text-center">
                <div class="border-top border-secondary w-75 mx-auto pt-2">
                    <small class="text-muted fw-semibold">Supplier Acceptance & Signature</small>
                </div>
            </div>
        </div>
    </div>

</body>
</html>
